### ISSUE TITLE
Cant print full output of some commands

### ISSUE THREAD

**Issue by nomad0812** [buckyroberts/Python-Reverse-Shell#15]
When executing commands like help from the server to a client on a windows machine, the command is output is not fully printed, basically any extremely long output commands are not fully printed

**Comment by N-faycal** [comment]
will be resolved tonight.
This may be a duplicate of bug #13

**Comment by N-faycal** [comment]
not related. It is due to the buffering. Working on it

**Comment by N-faycal** [comment]
Closed. Thanks for reporting
