### ISSUE TITLE
Netcat style shells

### ISSUE THREAD

**Issue by DarrenRainey** [buckyroberts/Python-Reverse-Shell#32]
Can you/how can I modify the server to accept shells such as ones used by netcat as currently they don't seem to connect or work

**Comment by DarrenRainey** [comment]
Correction Multi_Clients doesn't seem to work with netcat style shells

**Comment by roccomuso** [comment]
@DarrenRainey I made a "Turtle" porting in Node.js, that works also with netcat, check it out: [alveare](https://github.com/roccomuso/alveare)
